import Vue from "vue";

export const CMS_DOMAIN = "https://manage.uzncd.com";
export const AUTH_DOMAIN = "http://127.0.0.1:8000";

// DICTIONARY is used to handle different languages
export const DICTIONARY = {
  ru: {
    log_in: "Войти",
    registration: "Регистрация",
    vacancies: "Вакансии",
    about_company: "О компании",
    services: "Услуги",
    documents: "Документы",
    partners: "Партнеры",
    education: "Образование",
    faq: "Вопросы",
    contacts: "Контакты",
    our_mission: "Наша миссия",
    cooperation: "Сотрудничество",
    our_services: "Наши услуги",
    copyright: "2019 NCD. Все права защищены",
    close: "Закрыть",
    read_more: "Подробнее",
    candidates: "Аппликантов",
    employers: "Работодателей",
    year_of_exp: "Год опыта",
    name: "Имя",
    subject: "Тема",
    message: "Сообщение",
    send: "Отправить",
    navigation: "Навигация",
    about_us: "О нас",
    subscribe_mail: "Подпишитесь на рассылку",
    your: "Ваш",
    all_rights: "Все права защищены",
    main: "Главная",
    subscribe: "Подписаться",
    applicant_profile: "Профиль соискателя",
    applicant_profile_text: "Личная карточка для оценки квалификации",
    employment_abroad: "Трудоустройство за рубежом",
    employment_abroad_text: "Поможем найти достойную работу",
    help_with_visa: "Содействие в получении виз",
    help_with_visa_text: "Консультации по визовым вопросам",
    list_of_vacancies: "Список вакансий",
    vacancy: "Вакансия",
    country: "Страна",
    wages: "Заработная плата",
    apply: "Подать заявку",
    no_files: "Файлы не найдены.",
    not_authenticated: "Вы не авторизованы!",
    sign_in_or_register: "Войдите или зарегистрируйтесь",
    username: "Имя пользователя",
    password: "Пароль",
    select_role: "Выберите тип пользователя",
    employer: "Работодатель",
    candidate: "Аппликант",
    student: "Студент",
    select_from_list: "Выберите из списка",
    save: "Сохранить",
    empr_reg_form: "Регистрационная форма работодателя",
    company_name: "Название компании",
    boss_fullname: "Ф.И.О (первого руководителя)",
    email: "Э-почта",
    register_number: "Регистрационный номер",
    legal_address: "Юридический адрес",
    person_fullname_for_hiring: "Ф.И.О (ответственного лица)",
    phone: "Телефон",
    workers_amount: "Количество работников организации",
    terms_of_use: "Пользовательское соглашение",
    choose_files: "Выбрать файлы",
    company_name_tip:
      "Фирма, организация, учреждения, частного предпринимателялибо Ф.И.О физического лица",
    register_number_tip:
      "ИНН, номер социального страхования, либо другая информация об идентификации, которая подтверждает государственную регистрацию субъекта в качестве юридического",
    person_fullname_for_hiring_tip:
      "Ответственного лица за наем трудовых мигрантов",
    i_agree: "Я соглашаюсь с условиями",
    accept: "Принять",
    required_fields: "Объязательные поля",
    emp_reg_form: "Регистрационная форма аппликанта",
    fullname: "Ф.И.О",
    gender: "Пол",
    g_male: "Мужской",
    g_female: "Женский",
    passport_serial: "Серия паспорта",
    date_of_issue: "Дата выдачи",
    expiry_date: "Срок действия",
    tin: "ИНН",
    place_residence: "Место проживания",
    place_birth: "Место рождения",
    upload_avatar: "Загрузить аватарку",
    confirm_password: "Подтверждение пароля"
  },
  kz: {
    log_in: "Кіру",
    registration: "Тіркеу",
    vacancies: "Жұмыс орындары",
    about_company: "Компания туралы",
    services: "Қызметтер",
    documents: "Құжаттар",
    partners: "Серіктестер",
    education: "Білім",
    faq: "Сұрақтар",
    contacts: "Баыланыс мәліметтері",
    our_mission: "Біздің мыссыыамыз",
    cooperation: "Ынтымақтастық",
    our_services: "Біздің қызметтер",
    copyright: "2019 NCD. Барлық құқықтар сақталған",
    close: "Жабу",
    read_more: "Көбірек",
    candidates: "Кандидаттар",
    employers: "Жұмыс берушілер",
    employer: "Жұмыс беруші",
    year_of_exp: "Тәжірибе жылы",
    name: "Аты",
    subject: "Тақырып",
    message: "Мәтін",
    send: "Жіберіңіз",
    navigation: "Навигация",
    about_us: "Біз туралы",
    subscribe_mail: "Жаңалықтарға жазылыңыз",
    your: "Сіздің",
    all_rights: "Барлық құқықтар сақталған",
    main: "Басты бет",
    subscribe: "Жазылу",
    applicant_profile: "Өтініш берушінің профилі",
    applicant_profile_text: "Өтініш берушінің жеке картасы",
    employment_abroad: "Шетелде жұмыс істеу",
    employment_abroad_text: "Біз сізге лайықты жұмыс табуға көмектесеміз",
    help_with_visa: "Біз сізге лайықты жұмыс табуға көмектесеміз",
    help_with_visa_text: "Біз сізге виза бойынша кеңес береміз",
    list_of_vacancies: "Бос жұмыс орындары",
    vacancy: "Бос жұмыс орны",
    country: "Ел",
    wages: "Жалақы",
    apply: "Тапсырыс беру",
    no_files: "Файлдар табылмады.",
    not_authenticated: "Сіз расталмағансыз",
    sign_in_or_register: "Кіру немесе тіркелу",
    username: "Пайдаланушы аты",
    password: "Пароль",
    select_role: "Пайдаланушы рөлін таңдаңыз",
    candidate: "Кандидат",
    student: "Студент",
    select_from_list: "Тізімнен таңдаңыз",
    save: "Сақтау",
    empr_reg_form: "Жұмыс берушінің тіркеу нысаны",
    company_name: "Компанияның Аты",
    boss_fullname: "Бастықтың Т.А.Ә.",
    email: "Электрондық пошта",
    register_number: "Тіркеу нөмірі",
    legal_address: "Заңды мекен-жайы",
    person_fullname_for_hiring: "Жауапты тұлғаның Т.А.Ә.",
    phone: "Телефон",
    workers_amount: "Жұмысшылар саны",
    terms_of_use: "Қолдану ережелері",
    choose_files: "Файлдарды таңдаңыз",
    company_name_tip:
      "Фирма, ұйым, мекеме, жеке кәсіпкер немесе жеке тұлғаның Т.А.Ә.",
    register_number_tip:
      "ЖСН, әлеуметтік сақтандыру нөмірі немесе заңды тұлға ретінде мемлекеттік тіркеуді растайтын жеке басын куәландыратын ақпарат",
    person_fullname_for_hiring_tip:
      "Еңбек мигранттарын жалдау бойынша жауапты тұлға",
    i_agree: "Мен пайдалану шарттарымен келісемін",
    accept: "Қабылдаңыз",
    required_fields: "Міндетті өрістер",
    emp_reg_form: "Қызметкерлерді тіркеу нысаны",
    fullname: "Т.А.Ә.",
    gender: "Жынысы",
    g_male: "Еркек",
    g_female: "Әйел",
    passport_serial: "Паспорт сериясы",
    date_of_issue: "Берілген күні",
    expiry_date: "Қолданылу мерзімі",
    tin: "ЖСН",
    place_residence: "Тұрғылықты мекенжайы",
    place_birth: "Туған жер",
    upload_avatar: "Аватарды жүктеңіз",
    confirm_password: "Құпия сөзді растау"
  },
  en: {
    log_in: "Log in",
    registration: "Registration",
    vacancies: "Vacancies",
    about_company: "About company",
    services: "Services",
    documents: "Documents",
    partners: "Partners",
    education: "Education",
    faq: "FAQ",
    contacts: "Contacts",
    our_mission: "Our mission",
    cooperation: "Cooperation",
    our_services: "Our services",
    copyright: "2019 NCD. All rights reserved",
    close: "Close",
    read_more: "Read more",
    candidates: "Candidates",
    employers: "Employers",
    year_of_exp: "Year of experience",
    name: "Name",
    subject: "Subject",
    message: "Message",
    send: "Send",
    navigation: "Site map",
    about_us: "About us",
    subscribe_mail: "Sign up for the newsletter",
    your: "",
    all_rights: "All rights reserved",
    main: "Main page",
    subscribe: "Subscribe",
    applicant_profile: "Applicant profile",
    applicant_profile_text: "Personal qualification card",
    employment_abroad: "Employment abroad",
    employment_abroad_text: "We will help you find a decent job",
    help_with_visa: "Visa assistance",
    help_with_visa_text: "We will give you an advice on visa",
    list_of_vacancies: "List of vacancies",
    vacancy: "Vacancy",
    country: "Country",
    wages: "Wages",
    apply: "Apply",
    no_files: "No files were found.",
    not_authenticated: "You are not authenticated!",
    sign_in_or_register: "Sign in or register",
    username: "Username",
    password: "Password",
    select_role: "Select role of a user",
    employer: "Employer",
    candidate: "Сandidate",
    student: "Student",
    select_from_list: "Select from a list",
    save: "Save",
    empr_reg_form: "Employer registration form",
    company_name: "Company name",
    boss_fullname: "Fullname (first leader)",
    email: "Email",
    register_number: "Registration number",
    legal_address: "Legal address",
    person_fullname_for_hiring: "Fullname (responsible person)",
    phone: "Phone",
    workers_amount: "Number of employees",
    terms_of_use: "Terms of use",
    choose_files: "Choose files",
    i_agree: "I agree to the",
    accept: "Accept",
    required_fields: "Required fields",
    emp_reg_form: "Employer registration form",
    fullname: "Full name",
    gender: "Gender",
    g_male: "Male",
    g_female: "Female",
    passport_serial: "Passport №",
    date_of_issue: "Date of issue",
    expiry_date: "Expiry date",
    tin: "TIN",
    place_residence: "Place of residence",
    place_birth: "Place of birth",
    upload_avatar: "Upload your avatar",
    confirm_password: "Confirm password"
  },
  uz: {
    log_in: "Kirish",
    registration: "Ro'yxatdan o'tish",
    vacancies: "Ish o'rinlari",
    about_company: "Kompaniya haqida",
    services: "Xizmatlar",
    documents: "Hujjatlar",
    partners: "Hamkorlar",
    education: "Ta'lim",
    faq: "Savollar",
    contacts: "Kontaktlar",
    our_mission: "Bizning maqsadimiz",
    cooperation: "Hamkorlik",
    our_services: "Bizning xizmatlarimiz",
    copyright: "2019 NCD. Barcha huquqlar himoyalangan",
    close: "Yopish",
    read_more: "Batafsil",
    candidates: "Talabgorlar",
    employers: "Ish beruvchilar",
    year_of_exp: "Tajriba yili",
    name: "Ismi",
    subject: "Mavzu",
    message: "Matn",
    send: "Yuborish",
    navigation: "Navigatsiya",
    about_us: "Biz haqqimizda",
    subscribe_mail: "Yangiliklarga obuna boling",
    your: "",
    all_rights: "Barcha huquqlar himoyalangan",
    main: "Bosh sahifa",
    subscribe: "Obuna bo'lish",
    applicant_profile: "Arizachining anketasi",
    applicant_profile_text: "Shaxsiy malaka kartasi",
    employment_abroad: "Chet elda ishlash",
    employment_abroad_text: "Sizga munosib ish topishga yordam beramiz",
    help_with_visa: "Viza bo'yicha yordam",
    help_with_visa_text: "Viza bo'yicha maslahat",
    list_of_vacancies: "Bo'sh ish o'rinlar ro'yxatlari",
    vacancy: "Bo'sh ish o'rni",
    country: "Mamlakati",
    wages: "Oyligi",
    apply: "Ishga murojaat qilish",
    no_files: "Fayllar topilmadi.",
    not_authenticated: "Вы не авторизованы",
    sign_in_or_register: "Войдите в систему или зарегистрируйтесь",
    username: "Имя пользователя",
    password: "Parol",
    select_role: "Select role of a user",
    employer: "Employer",
    candidate: "Talabgor",
    student: "Talaba",
    select_from_list: "Ro'yxatdan tanlang",
    save: "Saqlab qo'yish",
    empr_reg_form: "Ish beruvchini ro'yxatdan o'tkazish formasi",
    company_name: "Kopmaniya nomi",
    boss_fullname: "Rahbarning to'liq ismi",
    email: "Elektron pochta",
    register_number: "Ro'yxatga olish raqami",
    legal_address: "Yuridik manzil",
    person_fullname_for_hiring: "Mas'ul shaxsning to'liq ismi",
    phone: "Telefon raqami",
    workers_amount: "Tashkilot ishchilari soni",
    terms_of_use: "Foydalanuvchi shartnomasi",
    choose_files: "Fayllarni tanlang",
    company_name_tip:
      "Firma, tashkilot, muassasa, xususiy tadbirkor yoki shaxsning to'liq ismi",
    register_number_tip:
      "TIN, ijtimoiy sug'urta raqami yoki boshqa shaxsni tasdiqlovchi ma'lumotlar, bu tashkilotning davlat ro'yxatiga olinganligini tasdiqlaydi",
    person_fullname_for_hiring_tip:
      "Mehnat muhojirlarini yollash uchun javobgar shaxs",
    i_agree: "Men foydalanuvchi shartnomasi shartlariga roziman",
    accept: "Qabul qilish",
    required_fields: "To'ldirilishi shart",
    emp_reg_form: "Xodimlarni ro'yxatdan o'tkazish shakli",
    fullname: "To'liq ismi",
    gender: "Jinsi",
    g_male: "Erkak",
    g_female: "Ayol",
    passport_serial: "Passport seriyasi",
    date_of_issue: "Berilgan sana",
    expiry_date: "Amal qilish muddati",
    tin: "TIN",
    place_residence: "Yashash joyi",
    place_birth: "Tug'ilgan joyi",
    upload_avatar: "Avataringizni yuklang",
    confirm_password: "Parolni tasdiqlang"
  }
};

export const eventBus = new Vue();

export const ga_id = "UA-149343577-2";

export const languages = {
  en: {
    image: require("~/static/pages/english-icon.png"),
    lang: "En"
  },
  ru: {
    image: require("~/static/pages/russian-icon.png"),
    lang: "Ru"
  },
  uz: {
    image: require("~/static/pages/uzbek-icon.png"),
    lang: "Uz"
  },
  kz: {
    image: require("~/static/pages/kazakh-icon.png"),
    lang: "Kz"
  }
};
