import Vue from "vue";

export const CMS_DOMAIN = "https://manage.uzncd.com";
export const AUTH_DOMAIN = "https://admin.uzncd.com";

// DICTIONARY is used to handle different languages
export const DICTIONARY = {
  ru: {
    log_in: "Войти",
    registration: "Регистрация",
    vacancies: "Вакансии",
    about_company: "О компании",
    services: "Услуги",
    documents: "Документы",
    partners: "Партнеры",
    education: "Образование",
    faq: "Вопросы",
    contacts: "Контакты",
    our_mission: "Наша миссия",
    cooperation: "Сотрудничество",
    our_services: "Наши услуги",
    copyright: "2019 NCD. Все права защищены",
    close: "Закрыть",
    read_more: "Подробнее",
    candidates: "Аппликантов",
    employers: "Работодателей",
    year_of_exp: "Год опыта",
    name: "Имя",
    subject: "Тема",
    message: "Сообщение",
    send: "Отправить",
    navigation: "Навигация",
    about_us: "О нас",
    subscribe_mail: "Подпишитесь на рассылку",
    your: "Ваш",
    all_rights: "Все права защищены",
    main: "Главная",
    subscribe: "Подписаться",
    applicant_profile: "Профиль соискателя",
    applicant_profile_text: "Личная карточка для оценки квалификации",
    employment_abroad: "Трудоустройство за рубежом",
    employment_abroad_text: "Поможем найти достойную работу",
    help_with_visa: "Содействие в получении виз",
    help_with_visa_text: "Консультации по визовым вопросам",
    list_of_vacancies: "Список вакансий",
    vacancy: "Вакансия",
    country: "Страна",
    wages: "Заработная плата",
    apply: "Подать заявку",
    no_files: "Файлы не найдены.",
    not_authenticated: "Вы не авторизованы!",
    sign_in_or_register: "Войдите или зарегистрируйтесь",
    username: "Имя пользователя",
    password: "Пароль",
    select_role: "Выберите тип пользователя",
    employer: "Работодатель",
    candidate: "Аппликант",
    student: "Студент",
    select_from_list: "Выберите из списка",
    save: "Сохранить",
    empr_reg_form: "Регистрационная форма работодателя",
    company_name: "Название компании",
    boss_fullname: "Ф.И.О (первого руководителя)",
    email: "Э-почта",
    register_number: "Регистрационный номер",
    legal_address: "Юридический адрес",
    person_fullname_for_hiring: "Ф.И.О (ответственного лица)",
    phone: "Телефон",
    workers_amount: "Количество работников организации",
    terms_of_use: "Пользовательское соглашение",
    choose_files: "Выбрать файлы",
    company_name_tip:
      "Фирма, организация, учреждения, частного предпринимателялибо Ф.И.О физического лица",
    register_number_tip:
      "ИНН, номер социального страхования, либо другая информация об идентификации, котораяподтверждает государственную регистрацию субъекта в качестве юридического",
    person_fullname_for_hiring_tip:
      "Ответственного лица за наем трудовых мигрантов",
    i_agree: "Я соглашаюсь с условиями",
    accept: "Принять",
    required_fields: "Объязательные поля",
    emp_reg_form: "Регистрационная форма аппликанта",
    fullname: "Ф.И.О",
    gender: "Пол",
    g_male: "Мужской",
    g_female: "Женский",
    passport_serial: "Серия паспорта",
    date_of_issue: "Дата выдачи",
    expiry_date: "Срок действия",
    tin: "ИНН",
    place_residence: "Место проживания",
    place_birth: "Место рождения",
    upload_avatar: "Загрузить аватарку",
    confirm_password: "Подтверждение пароля"
  },
  kz: {
    log_in: "Kіrý",
    registration: "Тіркеу",
    vacancies: "Jumys oryndary",
    about_company: "Kompanııa týraly",
    services: "Qyzmetter",
    documents: "Qujattar",
    partners: "Serіktester",
    education: "Bilim",
    faq: "Suraqtar",
    contacts: "Baılanys málіmetterі",
    our_mission: "Bіzdіń mıssııamyz",
    cooperation: "Yntymaqtastyq",
    our_services: "Bizdiñ qızmetterimiz",
    copyright: "2019 NCD. Barlıq quqıqtar saqtalğan",
    close: "Jabw",
    read_more: "Köbirek",
    candidates: "Kandïdattar",
    employers: "Jumıs berwşiler",
    employer: "Работодатель",
    year_of_exp: "Täjirïbe jılı",
    name: "Atı",
    subject: "Atawı",
    message: "Mätin",
    send: "Jiberiñiz",
    navigation: "Site map",
    about_us: "Navïgacïya",
    subscribe_mail: "Jañalıqqa jazılıñız",
    your: "",
    all_rights: "Barlıq quqıqtar qorğalğan",
    main: "Bastı bet",
    subscribe: "Jazılw",
    applicant_profile: "Ötiniş berwşiniñ profïli",
    applicant_profile_text: "Jeke biliktilik kartası",
    employment_abroad: "Şetelde jumıs istew",
    employment_abroad_text: "Biz sizge layıqtı jumıs tabwğa kömektesemizу",
    help_with_visa: "Vïzalıq kömek",
    help_with_visa_text: "Vïza boyınşa keñesşi",
    list_of_vacancies: "Bos jumıs orındarı",
    vacancy: "Bos jumıs ornı",
    country: "El",
    wages: "Jalaqı",
    apply: "Tapsırıs berw",
    no_files: "Fayldar tabılmadı.",
    not_authenticated: "Вы не авторизованы",
    sign_in_or_register: "Sign in or register",
    username: "Имя пользователя",
    password: "Пароль",
    select_role: "Выберите тип пользователя",
    candidate: "Аппликант",
    student: "Студент",
    select_from_list: "Выберите из списка",
    save: "Сохранить",
    empr_reg_form: "Регистрационная форма работодателя",
    company_name: "Название компании",
    boss_fullname: "Ф.И.О (первого руководителя)",
    email: "Э-почта",
    register_number: "Регистрационный номер",
    legal_address: "Юридический адрес",
    person_fullname_for_hiring: "Ф.И.О (ответственного лица)",
    phone: "Телефон",
    workers_amount: "Количество работников организации",
    terms_of_use: "Пользовательское соглашение",
    choose_files: "Выбрать файлы",
    company_name_tip:
      "Фирма, организация, учреждения, частного предпринимателялибо Ф.И.О физического лица",
    register_number_tip:
      "ИНН, номер социального страхования, либо другая информация об идентификации, котораяподтверждает государственную регистрацию субъекта в качестве юридического",
    person_fullname_for_hiring_tip:
      "Ответственного лица за наем трудовых мигрантов",
    i_agree: "Я соглашаюсь с условиями",
    accept: "Принять",
    required_fields: "Объязательно поле",
    emp_reg_form: "Регистрационная форма работника",
    fullname: "Ф.И.О",
    gender: "Пол",
    g_male: "Мужской",
    g_female: "Женский",
    passport_serial: "Серия паспорта",
    date_of_issue: "Дата выдачи",
    expiry_date: "Срок действия",
    tin: "ИНН",
    place_residence: "Место проживания",
    place_birth: "Место рождения",
    upload_avatar: "Загрузить аватарку",
    confirm_password: "Confirm password"
  },
  en: {
    log_in: "Log in",
    registration: "Registration",
    vacancies: "Vacancies",
    about_company: "About company",
    services: "Services",
    documents: "Documents",
    partners: "Partners",
    education: "Education",
    faq: "FAQ",
    contacts: "Contacts",
    our_mission: "Our mission",
    cooperation: "Cooperation",
    our_services: "Our services",
    copyright: "2019 NCD. All rights reserved",
    close: "Close",
    read_more: "Read more",
    candidates: "Candidates",
    employers: "Employers",
    year_of_exp: "Year of experience",
    name: "Name",
    subject: "Subject",
    message: "Message",
    send: "Send",
    navigation: "Site map",
    about_us: "About us",
    subscribe_mail: "Sign up for the newsletter",
    your: "Your",
    all_rights: "All rights reserved",
    main: "Main page",
    subscribe: "Subscribe",
    applicant_profile: "Applicant profile",
    applicant_profile_text: "Personal qualification card",
    employment_abroad: "Employment abroad",
    employment_abroad_text: "We will help you find a decent job",
    help_with_visa: "Visa assistance",
    help_with_visa_text: "We will give you an advice on visa",
    list_of_vacancies: "List of vacancies",
    vacancy: "Vacancy",
    country: "Country",
    wages: "Wages",
    apply: "Apply",
    no_files: "No files were found.",
    not_authenticated: "You are not authenticated!",
    sign_in_or_register: "Sign in or register",
    username: "Username",
    password: "Password",
    select_role: "Select role of a user",
    employer: "Employer",
    candidate: "Сandidate",
    student: "Student",
    select_from_list: "Select from a list",
    save: "Save",
    empr_reg_form: "Employer registration form",
    company_name: "Company name",
    boss_fullname: "Fullname (first leader)",
    email: "Email",
    register_number: "Registration number",
    legal_address: "Legal address",
    person_fullname_for_hiring: "Fullname (responsible person)",
    phone: "Phone",
    workers_amount: "Number of employees",
    terms_of_use: "Terms of use",
    choose_files: "Choose files",
    i_agree: "I agree to the",
    accept: "Accept",
    required_fields: "Required fields",
    emp_reg_form: "Employer registration form",
    fullname: "Full name",
    gender: "Gender",
    g_male: "Male",
    g_female: "Female",
    passport_serial: "Passport №",
    date_of_issue: "Date of issue",
    expiry_date: "Expiry date",
    tin: "TIN",
    place_residence: "Place of residence",
    place_birth: "Place of birth",
    upload_avatar: "Upload your avatar",
    confirm_password: "Confirm password"
  },
  uz: {
    log_in: "Kirish",
    registration: "Ro'yxatdan o'tish",
    vacancies: "Ish o'rinlari",
    about_company: "Kompaniya haqida",
    services: "Xizmatlar",
    documents: "Hujjatlar",
    partners: "Hamkorlar",
    education: "Ta'lim",
    faq: "Savollar",
    contacts: "Kontaktlar",
    our_mission: "Bizning maqsadimiz",
    cooperation: "Hamkorlik",
    our_services: "Bizning xizmatlarimiz",
    copyright: "2019 NCD. Barcha huquqlar himoyalangan",
    close: "Yopish",
    read_more: "Batafsil",
    candidates: "Talabgorlar",
    employers: "Ish beruvchilar",
    year_of_exp: "Tajriba yili",
    name: "Ismi",
    subject: "Mavzu",
    message: "Matn",
    send: "Yuborish",
    navigation: "Navigatsiya",
    about_us: "Biz haqqimizda",
    subscribe_mail: "Yangiliklarga obuna boling",
    your: "",
    all_rights: "Barcha huquqlar himoyalangan",
    main: "Bosh sahifa",
    subscribe: "Obuna bo'lish",
    applicant_profile: "Arizachining anketasi",
    applicant_profile_text: "Shaxsiy malaka kartasi",
    employment_abroad: "Chet elda ishlash",
    employment_abroad_text: "Sizga munosib ish topishga yordam beramiz",
    help_with_visa: "Viza bo'yicha yordam",
    help_with_visa_text: "Viza bo'yicha maslahat",
    list_of_vacancies: "Bo'sh ish o'rinlar ro'yxatlari",
    vacancy: "Bo'sh ish o'rni",
    country: "Mamlakati",
    wages: "Oyligi",
    apply: "Ishga murojaat qilish",
    no_files: "Fayllar topilmadi.",
    not_authenticated: "Вы не авторизованы",
    sign_in_or_register: "Войдите в систему или зарегистрируйтесь",
    username: "Имя пользователя",
    password: "Parol",
    select_role: "Select role of a user",
    employer: "Employer",
    candidate: "Аппликант",
    student: "Студент",
    select_from_list: "Выберите из списка",
    save: "Сохранить",
    empr_reg_form: "Employer registration form",
    company_name: "Название компании",
    boss_fullname: "Ф.И.О (первого руководителя)",
    email: "Э-почта",
    register_number: "Регистрационный номер",
    legal_address: "Юридический адрес",
    person_fullname_for_hiring: "Ф.И.О (ответственного лица)",
    phone: "Телефон",
    workers_amount: "Количество работников организации",
    terms_of_use: "Пользовательское соглашение",
    choose_files: "Выбрать файлы",
    company_name_tip:
      "Фирма, организация, учреждения, частного предпринимателялибо Ф.И.О физического лица",
    register_number_tip:
      "ИНН, номер социального страхования, либо другая информация об идентификации, котораяподтверждает государственную регистрацию субъекта в качестве юридического",
    person_fullname_for_hiring_tip:
      "Ответственного лица за наем трудовых мигрантов",
    i_agree: "I agree to the",
    accept: "Принять",
    required_fields: "Required fields",
    emp_reg_form: "Регистрационная форма работника",
    fullname: "Ф.И.О",
    gender: "Пол",
    g_male: "Мужской",
    g_female: "Женский",
    passport_serial: "Серия паспорта",
    date_of_issue: "Дата выдачи",
    expiry_date: "Срок действия",
    tin: "ИНН",
    place_residence: "Место проживания",
    place_birth: "Место рождения",
    upload_avatar: "Загрузить аватарку",
    confirm_password: "Confirm password"
  }
};

export const eventBus = new Vue();

export const ga_id = "UA-149343577-2";

export const languages = {
  en: {
    image: require("~/static/pages/english-icon.png"),
    lang: "En"
  },
  ru: {
    image: require("~/static/pages/russian-icon.png"),
    lang: "Ru"
  },
  uz: {
    image: require("~/static/pages/uzbek-icon.png"),
    lang: "Uz"
  },
  kz: {
    image: require("~/static/pages/kazakh-icon.png"),
    lang: "Kz"
  }
};
